version: '3'
services:
    php-apache:
        build: ./
        ports:
            - 80:80
        volumes:
            - ./ApacheRoot:/var/www/html:z
        links:
            - 'mariadb'

    mariadb:
        image: mariadb:latest
        volumes:
            - ./mariadb:/var/lib/mysql
        ports:
            - '3306:3306'
        environment:
            TZ: "Europe/Berlin"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "tester"
    
    phpmyadmin:
        depends_on:
            - mariadb
        image: phpmyadmin:latest
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: mariadb
            MYSQL_ROOT_PASSWORD: tester 

volumes:
    mariadb: